import { Router } from "express";
import { z } from "zod";
import { requireAdmin, writeAuditLog } from "../auth";
import { serviceUnavailable, supabaseRequest } from "../db";
export const adminCouponsRouter=Router();adminCouponsRouter.use(requireAdmin);
adminCouponsRouter.get("/",async(_req,res)=>{try{res.json(await supabaseRequest("coupons?select=*&order=created_at.desc"));}catch(e){res.status(serviceUnavailable(e)?503:500).json({error:"Unable to load coupons."});}});
adminCouponsRouter.post("/",async(req,res)=>{const p=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{2,64}$/),discount:z.number().gt(0).lte(100),active:z.boolean().default(true)}).safeParse(req.body);if(!p.success){res.status(400).json({error:"Invalid coupon.",details:p.error.flatten()});return;}try{const out=await supabaseRequest("coupons",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(p.data)});await writeAuditLog("coupon.create",req.admin?.id,{code:p.data.code});res.status(201).json(out);}catch(e){res.status(serviceUnavailable(e)?503:409).json({error:"Unable to create coupon."});}});
adminCouponsRouter.patch("/:code",async(req,res)=>{const p=z.object({discount:z.number().gt(0).lte(100).optional(),active:z.boolean().optional()}).safeParse(req.body);if(!p.success){res.status(400).json({error:"Invalid coupon."});return;}try{res.json(await supabaseRequest(`coupons?code=eq.${encodeURIComponent(req.params.code.toUpperCase())}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(p.data)}));}catch(e){res.status(serviceUnavailable(e)?503:500).json({error:"Unable to update coupon."});}});
adminCouponsRouter.delete("/:code",async(req,res)=>{try{await supabaseRequest(`coupons?code=eq.${encodeURIComponent(req.params.code.toUpperCase())}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({active:false})});await writeAuditLog("coupon.disable",req.admin?.id,{code:req.params.code});res.status(204).send();}catch(e){res.status(serviceUnavailable(e)?503:500).json({error:"Unable to disable coupon."});}});
