create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  name text not null,
  name_en text,
  price numeric(12,2) not null check (price >= 0),
  original_price numeric(12,2),
  sale_price numeric(12,2),
  category text not null,
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  description text,
  description_en text,
  badge text,
  tag text,
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  video text,
  stock integer not null default 0 check (stock >= 0),
  low_stock_threshold integer not null default 3 check (low_stock_threshold >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  idempotency_key text not null unique,
  customer_name text not null,
  phone text not null,
  address text not null,
  notes text,
  payment_method text not null check (payment_method in ('cod','wallet','instapay')),
  transfer_number text,
  receipt_path text,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  total numeric(12,2) not null check (total >= 0),
  coupon_code text,
  status text not null default 'جديد',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  original_unit_price numeric(12,2),
  discount_amount numeric(12,2) not null default 0,
  total numeric(12,2) not null check (total >= 0)
);

create table if not exists public.coupons (
  code text primary key,
  discount numeric(5,2) not null check (discount > 0 and discount <= 100),
  uses integer not null default 0 check (uses >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name_ar text not null,
  name_en text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists slug text;
update public.products set slug = id where slug is null;
alter table public.products alter column slug set not null;
alter table public.products add column if not exists category_id uuid references public.categories(id);

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products(id) on delete cascade,
  size text not null,
  color text not null,
  sku text unique,
  stock integer not null default 0 check (stock >= 0),
  reserved_stock integer not null default 0 check (reserved_stock >= 0),
  unique (product_id, size, color)
);

alter table public.order_items add column if not exists variant_id uuid references public.product_variants(id);
alter table public.order_items add column if not exists size_snapshot text;
alter table public.order_items add column if not exists color_snapshot text;
alter table public.orders add column if not exists public_reference text;
update public.orders set public_reference = id where public_reference is null;
alter table public.orders alter column public_reference set not null;
create unique index if not exists orders_public_reference_idx on public.orders(public_reference);

create index if not exists products_active_category_idx on public.products(is_active, category);
create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists variants_product_idx on public.product_variants(product_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

create table if not exists public.coupon_redemptions (
  id uuid primary key default gen_random_uuid(),
  coupon_code text not null references public.coupons(code),
  order_id text not null references public.orders(id) on delete cascade,
  unique (coupon_code, order_id)
);

create table if not exists public.site_settings (
  key text primary key,
  value_json jsonb not null,
  updated_by uuid references public.admin_users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.uploads (
  id uuid primary key default gen_random_uuid(),
  storage_key text unique not null,
  owner_type text not null,
  owner_id text not null,
  mime_type text not null,
  size_bytes integer not null check (size_bytes > 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.store_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.coupons enable row level security;
alter table public.categories enable row level security;
alter table public.product_variants enable row level security;
alter table public.coupon_redemptions enable row level security;
alter table public.site_settings enable row level security;
alter table public.uploads enable row level security;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists settings_set_updated_at on public.store_settings;
create trigger settings_set_updated_at before update on public.store_settings for each row execute function public.set_updated_at();

 do $$ begin
  create policy products_public_read on public.products for select using (is_active = true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy settings_public_read on public.store_settings for select using (true);
exception when duplicate_object then null; end $$;

create or replace function public.create_store_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p jsonb := payload;
  existing jsonb;
  item jsonb;
  product_row public.products%rowtype;
  order_id text := coalesce(nullif(p->>'id',''), 'NN-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint::text);
  key text := nullif(p->>'idempotency_key','');
  subtotal numeric := 0;
  discount numeric := 0;
  shipping numeric := greatest(0, coalesce((p->>'shipping_amount')::numeric, 0));
  coupon_discount numeric := 0;
  line_total numeric;
begin
  if key is null then raise exception using errcode = '22023', message = 'idempotency_key is required'; end if;
  select to_jsonb(o) into existing from orders o where o.idempotency_key = key;
  if existing is not null then return existing; end if;

  for item in select * from jsonb_array_elements(coalesce(p->'items','[]'::jsonb)) loop
    select * into product_row from products where id = item->>'product_id' and is_active = true for update;
    if not found then raise exception using errcode = 'P0001', message = 'Product is unavailable: ' || (item->>'product_id'); end if;
    if product_row.stock < (item->>'quantity')::integer then raise exception using errcode = 'P0001', message = 'Insufficient stock for: ' || product_row.id; end if;
    line_total := product_row.price * (item->>'quantity')::integer;
    subtotal := subtotal + line_total;
    update products set stock = stock - (item->>'quantity')::integer, updated_at = now() where id = product_row.id;
  end loop;
  if nullif(p->>'coupon_code','') is not null then
    select discount into coupon_discount from coupons where code = upper(p->>'coupon_code') and active = true;
    if coupon_discount is null then raise exception using errcode = 'P0001', message = 'Invalid coupon'; end if;
    discount := round(subtotal * coupon_discount / 100, 2);
    update coupons set uses = uses + 1 where code = upper(p->>'coupon_code');
  end if;
  insert into orders (id,idempotency_key,customer_name,phone,address,notes,payment_method,transfer_number,receipt_path,subtotal,discount_amount,shipping_amount,total,coupon_code)
  values (order_id,key,p->>'customer_name',p->>'phone',p->>'address',p->>'notes',p->>'payment_method',p->>'transfer_number',p->>'receipt_path',subtotal,discount,shipping,greatest(0,subtotal-discount+shipping),nullif(upper(p->>'coupon_code'),''));
  for item in select * from jsonb_array_elements(coalesce(p->'items','[]'::jsonb)) loop
    select * into product_row from products where id = item->>'product_id';
    insert into order_items (order_id,product_id,name,quantity,unit_price,total) values (order_id,product_row.id,coalesce(item->>'name',product_row.name),(item->>'quantity')::integer,product_row.price,product_row.price*(item->>'quantity')::integer);
  end loop;
  select to_jsonb(o) || jsonb_build_object('order_items',(select coalesce(jsonb_agg(to_jsonb(i)),'[]'::jsonb) from order_items i where i.order_id=o.id)) into existing from orders o where o.id=order_id;
  return existing;
exception when unique_violation then
  select to_jsonb(o) into existing from orders o where o.idempotency_key=key;
  if existing is not null then return existing; else raise; end if;
end;
$$;
